### ISSUE TITLE
File name issue

### ISSUE THREAD

**Issue by radhe** [nikunj1091/fb_photo_album#2]
File name should have query parameters.

**Comment by radhe** [comment]
Fine names still have query parameters

**Comment by nikunj1091** [comment]
query parameter means?????????

**Comment by radhe** [comment]
http://en.wikipedia.org/wiki/Query_string
![screen_shot_2014-11-05_at_8_27_43_pm](https://cloud.githubusercontent.com/assets/1138674/4919680/480f1ac4-64fc-11e4-9ee2-41515e4a56ea.png)
